version: '3.8'

services:
   review-service:
      container_name: review-service
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - '8080:8080' # Maps container's port 8080 to host
      environment:
         - DATABASE_URL=postgresql://postgres:postgres@review-db:5432/reviewdb
      depends_on:
         - review-db
      networks:
         - backend

   review-db:
      image: postgres:13
      container_name: review-db
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: reviewdb
      ports:
         - '5432:5432'
      networks:
         - backend
      volumes:
         - review_db_data:/var/lib/postgresql/data

networks:
   backend:
      driver: bridge

volumes:
   review_db_data:
